### ISSUE TITLE
REST or GraphQL?

### ISSUE THREAD

**Issue by XzAeRo** [BoxOfficeInitiative/backend-api#3]
We need to decide **NOW** which route should we follow @BoxOfficeInitiative/backend 

A nice read about it: 
* https://blog.apollographql.com/graphql-vs-rest-5d425123e34b
* https://medium.com/codingthesmartway-com-blog/rest-vs-graphql-418eac2e3083

In my opinion, GraphQL seems to be the most "smart" and atomic (one request can fetch multiple elements), but REST still is the king of simplicity and developer friendliness.

I vote for GraphQL.

**Comment by degoeym** [comment]
Do we know how easy or difficult it is to setup a .Net Core project to use GraphQL? I know REST is pretty straight forward.

Possibly useful links:

https://graphql.org/code/#c-net
https://developer.okta.com/blog/2019/04/16/graphql-api-with-aspnetcore

**Comment by XzAeRo** [comment]
After looking at the dotnet resources, it seems more tempting to go with REST. Really more straightforward to implement, and better core support too.

**Comment by degoeym** [comment]
Agreed. GraphQL looks nifty, but may not be the right direction for the moment.

**Comment by XzAeRo** [comment]
In this first iteration we will go with REST.

If anyone feels that we shouldn't, please feel free to create a PR with a proposal.
